### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by MrBrights** [PyvesB/advanced-achievements#1040]
[20:30:50] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AdvancedAchievements v7.1.0
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:939) [?:?]
	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:887) ~[patched_1.16.5.jar:git-Purpur-1126]
	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:761) ~[patched_1.16.5.jar:git-Purpur-1126]
	at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:858) ~[patched_1.16.5.jar:git-Purpur-1126]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:234) ~[patched_1.16.5.jar:git-Purpur-1126]
[20:30:50] [Server thread/ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
	at java.lang.Thread.stop(Thread.java:939) [?:?]
	at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:887) ~[patched_1.16.5.jar:git-Purpur-1126]
	at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:761) ~[patched_1.16.5.jar:git-Purpur-1126]
	at net.minecraft.server.v1_16_R3.MinecraftServer.close(MinecraftServer.java:858) ~[patched_1.16.5.jar:git-Purpur-1126]
	at org.spigotmc.WatchdogThread.run(WatchdogThread.java:234) ~[patched_1.16.5.jar:git-Purpur-1126]

**Comment by PyvesB** [comment]
Hello @MrBrights ! 👋🏻 

You've not used the issue template, there's unfortunately very little information to help you. However, the error `Main thread terminated by WatchDog due to hard crash java.lang.ThreadDeath: null` suggests the problem isn't with Advanced Achievements. Once Watch Dog has kicked in, all subsequent actions, including passing BlockBreakEvents to Advanced Achievements, will fail.

**Comment by PyvesB** [comment]
No evidence of this being a problem with Advanced Achievements, will close for now. :)
