### ISSUE TITLE
Unable to connect to the intranet database

### ISSUE THREAD

**Issue by SheerYin** [PyvesB/advanced-achievements#1076]
### 🎆 Advanced Achievements version

AdvancedAchievements-7.2.3

### 🖥 Server version

purpur-1.17.1-1397

### 🚰 Spigot username

purpur

### 𝑾 Wiki read

- [X] I have read the Wiki.

### 📁 Existing issues

- [X] I have searched existing issues.

### 🐛 Description

When connecting to the local database (127.0.0.1), no error is reported normally
When connecting to the intranet database (192.168.x.x), an error is reported
Even a new database 

Other plug-ins can be connected to the intranet, such as lcukperms

### 📄 Server logs

```

```
[17:21:33] [Server thread/ERROR]: [AdvancedAchievements] Database error while removing descriptions:
java.sql.SQLSyntaxErrorException: Can't DROP 'description'; check that column/key exists
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[patched_1.17.1.jar:git-Purpur-1397]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[patched_1.17.1.jar:git-Purpur-1397]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:762) ~[patched_1.17.1.jar:git-Purpur-1397]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:646) ~[patched_1.17.1.jar:git-Purpur-1397]
	at com.hm.achievement.db.DatabaseUpdater.removeAchievementDescriptions(DatabaseUpdater.java:187) ~[AdvancedAchievements-7.2.3.jar:?]
	at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:107) ~[AdvancedAchievements-7.2.3.jar:?]
	at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:132) ~[AdvancedAchievements-7.2.3.jar:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:49) ~[AdvancedAchievements-7.2.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1397]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1397]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1397]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Purpur-1397]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Purpur-1397]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:727) ~[patched_1.17.1.jar:git-Purpur-1397]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:318) ~[patched_1.17.1.jar:git-Purpur-1397]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1216) ~[patched_1.17.1.jar:git-Purpur-1397]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1397]
	at java.lang.Thread.run(Thread.java:831) [?:?]

### ⚙ Configuration

```

```
DatabaseAddress: jdbc:mysql://192.168.x.x:6151/survival_advancedachievements
DatabaseUser: root
DatabasePassword: '******'

**Comment by PyvesB** [comment]
Hello @SheerYin ! 👋🏻 

Which version of MySQL are you using? Did you happen to upgrade from an older version of the plugin?

**Comment by SheerYin** [comment]
> Hello @SheerYin ! 👋🏻
> 
> Which version of MySQL are you using? Did you happen to upgrade from an older version of the plugin?

mysql-installer-community-8.0.23.0 

No, even if you use a new empty database (without any data), but still connect to the intranet mysql normally, this error is still reported

**Comment by PyvesB** [comment]
So, what is the the difference between the local and the intranet databases? Are they running different MySQL versions? Are they somehow configured differently?

**Comment by SheerYin** [comment]
> So, what is the the difference between the local and the intranet databases? Are they running different MySQL versions? Are they somehow configured differently?

all the same

**Comment by PyvesB** [comment]
Have you set a different value of `TablePrefix` in _config.yml_ for the two databases by any chance?

**Comment by SheerYin** [comment]
> Have you set a different value of in _config.yml_ for the two databases by any chance?`TablePrefix`

In the default setting, there is no TablePrefix
And also did not set TablePrefix
Are all consistent

**Comment by PyvesB** [comment]
Does the error still happen when Advanced Achievements is the _only_ plugin installed on the server?

**Comment by PyvesB** [comment]
The next version of the plugin will no longer contain the problematic bit of code (see fcc434ec02285743e8a15b0030c70a009efc009e), so I'll go ahead and close this. 😉

**Comment by SheerYin** [comment]
> The next version of the plugin will no longer contain the problematic bit of code (see [fcc434e](https://github.com/PyvesB/advanced-achievements/commit/fcc434ec02285743e8a15b0030c70a009efc009e)), so I'll go ahead and close this. 😉

I updated to the latest version and it has been resolved, thank you very much
