### ISSUE TITLE
 Could not pass event InventoryClickEvent

### ISSUE THREAD

**Issue by jusobreira** [PyvesB/advanced-achievements#836]
* Advanced Achievements version: 
![image](https://user-images.githubusercontent.com/10175304/91856869-806cde00-ec3d-11ea-8333-c6d738512cd5.png)

* Minecraft version: 
![image](https://user-images.githubusercontent.com/10175304/91856913-8e226380-ec3d-11ea-9853-f976341420df.png)

* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched:  Yes, found similar issues but not figured out a solution

:question: **Help request**

I'm heaving a error when a player click at EatenItems, DistanceHorse and HoePlowings

The Config file: https://pastebin.com/j6ksiX7f
```

[09:22:48 ERROR]: Could not pass event InventoryClickEvent to AdvancedAchievements v6.2.0
java.lang.NullPointerException: null
        at com.hm.achievement.utils.RewardParser.getRewardListing(RewardParser.java:101) ~[?:?]
        at com.hm.achievement.gui.CategoryGUI.buildLore(CategoryGUI.java:431) ~[?:?]
        at com.hm.achievement.gui.CategoryGUI.displayPage(CategoryGUI.java:219) ~[?:?]
        at com.hm.achievement.gui.CategoryGUI.displayCategoryGUI(CategoryGUI.java:145) ~[?:?]
        at com.hm.achievement.listener.ListGUIListener.onInventoryClick(ListGUIListener.java:71) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor863.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-135]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-135]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2423) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-135]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-135]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

```

**Comment by PyvesB** [comment]
Hello @jusobreira ,

The error is a bit obscure, but I think this is happening because you omitted the quantity for the `Item` rewards for some of the achievements in those categories (i.e. `Item: Cake` -> `Item: Cake 1`). :)

**Comment by jusobreira** [comment]
That was exactly the problem. Thanks very much!
