### ISSUE TITLE
Problem with latest version of LuckPerms

### ISSUE THREAD

**Issue by kelso6969** [PyvesB/advanced-achievements#892]
:information_source: **Basic information**

* Advanced Achievements version: 6.7.0 and 6.7.1
* Minecraft version: 1.16.4 / Paper-267
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes, luckperms just updated yesterday and see no related issues.

:beetle: **Description**

install 5.3.32 luckperms

:page_facing_up: **Server logs**

````

[09:35:11 ERROR]: Could not pass event PlayerDropItemEvent to AdvancedAchievements v6.7.1
com.hm.achievement.exception.DatabaseReadError: Database read error while retrieving ItemDrops statistics.
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:42) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.getNormalAchievementAmount(AbstractDatabaseManager.java:370) ~[?:?]
        at com.hm.achievement.db.CacheManager.getAndIncrementStatisticAmount(CacheManager.java:164) ~[?:?]
        at com.hm.achievement.listener.statistics.AbstractListener.updateStatisticAndAwardAchievementsIfAvailable(AbstractListener.java:54) ~[?:?]
        at com.hm.achievement.listener.statistics.DropsListener.onPlayerDropItem(DropsListener.java:36) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor740.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-276]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-276]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-276]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.EntityHuman.a(EntityHuman.java:587) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1970) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.EntityHuman.dropItem(EntityHuman.java:538) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1450) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-276]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLSyntaxErrorException: (conn=4093958) Could not set parameter in setObject, could not convert: class java.util.UUID to 1
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:171) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setInternalObject(BasePrepareStatement.java:1149) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setObject(BasePrepareStatement.java:844) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.lambda$getNormalAchievementAmount$8(AbstractDatabaseManager.java:363) ~[?:?]
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:37) ~[?:?]
        ... 27 more
[09:35:18 WARN]: [AdvancedAchievements] Task #595 for AdvancedAchievements v6.7.1 generated an exception
com.hm.achievement.exception.DatabaseReadError: Database read error while retrieving DistanceFoot statistics.
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:42) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.getNormalAchievementAmount(AbstractDatabaseManager.java:370) ~[?:?]
        at com.hm.achievement.db.CacheManager.getAndIncrementStatisticAmount(CacheManager.java:164) ~[?:?]
        at com.hm.achievement.runnable.AchieveDistanceRunnable.updateDistance(AchieveDistanceRunnable.java:143) ~[?:?]
        at com.hm.achievement.runnable.AchieveDistanceRunnable.validateMovementAndUpdateDistance(AchieveDistanceRunnable.java:108) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
        at com.hm.achievement.runnable.AchieveDistanceRunnable.run(AchieveDistanceRunnable.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-276]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-276]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLSyntaxErrorException: (conn=4093958) Could not set parameter in setObject, could not convert: class java.util.UUID to 1
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:171) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setInternalObject(BasePrepareStatement.java:1149) ~[?:?]
        at me.lucko.luckperms.lib.mariadb.BasePrepareStatement.setObject(BasePrepareStatement.java:844) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.lambda$getNormalAchievementAmount$8(AbstractDatabaseManager.java:363) ~[?:?]
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:37) ~[?:?]
        ... 15 more



````
running Paper(276), luckperms 2.5.32

Reverting back to luckperms 5.1.93 resolves this issue.

:wrench: **Configuration**

````

````

**Comment by PyvesB** [comment]
Hello @kelso6969 ! 👋🏻 

Thanks for the details. I'll try to reproduce over the weekend. Which database type are you using?

**Comment by PyvesB** [comment]
Looking more closely at the stack traces, they suggest you're using Advanced Achievements with MySQL. One of the recent LuckPerm commits (https://github.com/lucko/LuckPerms/commit/00d4a2a1dac1b4ebcb067f746010b35d8c889669) seems to have updated the MySQL and MariaDB database drivers, and those apparently have breaking changes with regards to UUID handling.

CraftBukkit, Spigot and other server software ship their own database drivers for both SQLite and MySQL, and plugin authors generally should use those rather than shipping their own. You can see it as a common and standard set of drivers that every plugin has agreed on and can confidently rely on. Here, LuckPerms has effectively forced its own set of database drivers onto everyone else, which isn't great. This means that any Minecraft plugin using MySQL will behave differently or break when LuckPerms is added to a server, which is what you have observed here. At the very least, things will be confusing for users, as errors will have `me.lucko.luckperms` elements intertwined with other plugins in stacktraces, due to the way LuckPerms relocates its database drivers.

It's really unfortunate that other plugins are messing with the standard drivers shipped by Spigot, but for now I've pushed a workaround that should solve the immediate problem.
