### ISSUE TITLE
AA stops after MySQL error since version 6.7.2

### ISSUE THREAD

**Issue by schnubbi3083** [PyvesB/advanced-achievements#897]
:information_source: **Basic information**

* Advanced Achievements version: 6.7.2
* Minecraft version: Papermc 1.16.4 Build 288
  read: yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: yes

:beetle: New MySQL Error since last update 

Since i updated to 6.7.2 i get this error when somebody tries to open /aach.

In the version before all was ok.

MySQL cerdentials checked more then once.

Database is MariaDB 10.4

````
[00:20:39] [Server thread/INFO]: schnubbi3083 issued server command: /aachievements
[00:20:39] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'aachievements' in plugin AdvancedAchievements v6.7.2 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2008) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1819) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1772) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-288]
	at java.lang.Thread.run(Thread.java:834) [?:?]
````

````
#=============================OOO=============================#
# III-----------------------------------------------------III #
# |                    Database settings                    | #
# 3---------------------------------------------------------3 #
#=============================ooo=============================#
# Make a daily backup of your local database (if sqlite or h2).
DatabaseBackup: true

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: mysql

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: ''

# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ''

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: jdbc:mysql://localhost:3306/achievement
DatabaseUser: secret
DatabasePassword: secret

````

**Comment by PyvesB** [comment]
Hello @schnubbi3083! 👋🏻 

There must be another error earlier in the logs highlighting what the problem is, could you please share it?

**Comment by PyvesB** [comment]
Worth noting that I've just tried with fresh installations of MySQL 5.7.32 and 8.0.22, everything works fine as far as I can tell. No problems to report on H2, SQLite or PostgreSQL either.

**Comment by schnubbi3083** [comment]
´´´´
[15:17:54] [Server thread/ERROR]: [AdvancedAchievements] Error while attempting to retrieve a connection to the database:
java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3306)(type=master) : (conn=45633) Access denied for user 'MC'@'localhost' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1385) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.util.Utils.retrieveProxy(Utils.java:635) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.MariaDbConnection.newConnection(MariaDbConnection.java:150) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.Driver.connect(Driver.java:89) ~[?:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:251) ~[java.sql:?]
	at com.hm.achievement.db.AbstractRemoteDatabaseManager.createSQLConnection(AbstractRemoteDatabaseManager.java:51) ~[?:?]
	at com.hm.achievement.db.AbstractDatabaseManager.getSQLConnection(AbstractDatabaseManager.java:158) ~[?:?]
	at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:102) ~[?:?]
	at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:145) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-288]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLInvalidAuthorizationSpecException: (conn=45633) Access denied for user 'MC'@'localhost' (using password: YES)
Current charset is UTF-8. If password has been set using other charset, consider using option 'passwordCharacterEncoding'
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:187) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:760) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:546) ~[?:?]
	at nl.chimpgamer.networkmanager.lib.mariadb.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1380) ~[?:?]
	... 20 more
[15:17:54] [Server thread/ERROR]: [AdvancedAchievements] A non recoverable error was encountered while loading the plugin, disabling it:
com.hm.achievement.exception.PluginLoadError: Failed to establish database connection. Please verify your settings in config.yml.
	at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:105) ~[?:?]
	at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:145) ~[?:?]
	at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-288]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-288]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-288]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[15:17:54] [Server thread/INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v6.7.2
´´´´

**Comment by PyvesB** [comment]
The password encoding seems wrong. I don't think it will work when you revert back to the previous version of the plugin you were using, could you please confirm?

**Comment by schnubbi3083** [comment]
Yes, it doesn't work at all. Curious, because i used it before the last update every day .....

**Comment by PyvesB** [comment]
Worth deleting and re-entering the password in the configuration file. The database claims it uses "UTF-8", so you need to configure your text editor to use the same encoding. Typically this will not be the case if you open up the config on a Windows machine and reupload it onto your Linux server. Any special characters that you've included in the password may be messed up.

**Comment by schnubbi3083** [comment]
That's also curiuos beciause i only use the in WinSCP integrated, Notepad++ or jed editor. But i will try to active set the encoding to UTF-8.

I will then report :-)

**Comment by schnubbi3083** [comment]
So: Made it to ansi then, made it back to UTF-8 - same error.
Try it with ANSI - same error. No clue what happening between 2 days ago and now. Same database, same config and a new error....

**Comment by PyvesB** [comment]
This is a tricky one.

After each attempt, did you perform a full server restart? _/aach reload_ won't be enough in this case.

Did you change anything else on the server? For example updating any other plugin? A LuckPerms update cause a conflict recently (see #892).

Do you have any other plugins connecting to the same database?

**Comment by schnubbi3083** [comment]
Yes there are 6 other plugins with database connection. All are working, a inventory synchronisation included. If there is going something wrong with the database i would recognise it at this iventory syncing thing very fast.

Yes, of course i do a full server restart.

**Comment by PyvesB** [comment]
> And yes i updatet a plugin together with AdvancedAchievement. It's my perm tool: NetworkManager. It is not Luckperms but do the same with an live webfrontend. But to be honest i need this perm plugin update because it fixed a lot of bad perm errors. What can i do to try it out and is there a workaround perhaps ?

It's a least worth temporarily trying to downgrade NetworkManager and see if Advanced Achievements starts working again. In the stack traces you shared in https://github.com/PyvesB/advanced-achievements/issues/897#issuecomment-732191689, you'll notice that `nl.chimpgamer.networkmanager.lib.mariadb` comes up quite a lot, so I'm increasingly thinking it's a repeat of what I've described in https://github.com/PyvesB/advanced-achievements/issues/892#issuecomment-727199709. You should probably open a bug report with NetworkManager and also point the maintainers to https://github.com/lucko/LuckPerms/issues/2721. Ultimately the LuckPerms author agreed this was a problem in his plugin and pushed some fixes that NetworkManager may be able to reproduce in their own implementation.

**Comment by PyvesB** [comment]
@schnubbi3083 any news from the NetworkManager  author? I did see that the latest changelog contained the following entry:

> Should have fixed mysql and mariadb conflicts with other plugins.

I'm assuming this problem is now fixed?

**Comment by schnubbi3083** [comment]
Yes, is fixed.... sorry had a lot of work so i forgot to close this :-)
