### ISSUE TITLE
Demo available?

### ISSUE THREAD

**Issue by dmetzler1988** [PyvesB/advanced-achievements#941]
:information_source: **Basic information**

* Advanced Achievements version: latest
* Minecraft version: 1.16.3

:question: **Help request**

Hello,
the plugin seems to be what i am looking for. But i would like to see it in action and would like to test it on my server before i buy it.

Is there a server where i can test it? Like a Demo-Server with admin access (which will be resetted after tests)? A Demo-Server without admin access will also be nice - to see it in action.
Or do you have a time-limited test-version which i can implement on my test-server? Then i can check if it will work with my plugins (BetterBees, Clearlag, EssentialsX, LWCX, mcMMO, Multiverse, openinv, permissionsEx, Vault, WorldBorder, WorldEdit, WorldGuard) on MC version 1.16.3.

Best regards

**Comment by PyvesB** [comment]
Hello @dmetzler1988! 👋🏻 

You can try out the old version: https://www.spigotmc.org/resources/advanced-achievements-outdated.6239/

Otherwise, you're free to check out the source code and build it to generate your own test version.

**Comment by dmetzler1988** [comment]
Hi @PyvesB 

thanks for your fast reply!
I will try the old version later.

I had checked out the source code and had build it with intelliJ (as you described on dev-docu), but the generated AdvancedAchievements throws a lot of errors, when i tried the commands and gui. So i think something is wrong with my build.

```
[17:14:16] [Server thread/WARN]: [AdvancedAchievements] Task #37 for AdvancedAchievements v6.7.2 generated an exception
java.lang.NullPointerException: null
	at com.hm.achievement.utils.StatisticIncreaseHandler.shouldIncreaseBeTakenIntoAccount(StatisticIncreaseHandler.java:121) ~[?:?]
	at com.hm.achievement.listener.statistics.ConnectionsListener.lambda$scheduleAwardConnection$0(ConnectionsListener.java:87) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[17:14:24] [Server thread/WARN]: [AdvancedAchievements] Task #15 for AdvancedAchievements v6.7.2 generated an exception
java.lang.NullPointerException: null
	at com.hm.achievement.utils.StatisticIncreaseHandler.shouldIncreaseBeTakenIntoAccount(StatisticIncreaseHandler.java:121) ~[?:?]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.updateTime(AchievePlayTimeRunnable.java:70) ~[?:?]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.lambda$run$0(AchievePlayTimeRunnable.java:59) ~[?:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_281]
	at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_281]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.run(AchievePlayTimeRunnable.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[17:14:35] [Server thread/INFO]: l_KyRiOs_l issued server command: /ach
[17:14:35] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to AdvancedAchievements v6.7.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1689) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.hm.achievement.listener.statistics.PlayerCommandsListener.onPlayerCommand(PlayerCommandsListener.java:41) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	... 19 more
[17:14:58] [Server thread/INFO]: l_KyRiOs_l issued server command: /aach
[17:14:58] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to AdvancedAchievements v6.7.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1689) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.hm.achievement.listener.statistics.PlayerCommandsListener.onPlayerCommand(PlayerCommandsListener.java:41) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	... 19 more
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:14:58] [Server thread/WARN]: [AdvancedAchievements] Failed to display clickable and hoverable message in /aach help command. Displaying standard message instead.
[17:15:24] [Server thread/WARN]: [AdvancedAchievements] Task #15 for AdvancedAchievements v6.7.2 generated an exception
java.lang.NullPointerException: null
	at com.hm.achievement.utils.StatisticIncreaseHandler.shouldIncreaseBeTakenIntoAccount(StatisticIncreaseHandler.java:121) ~[?:?]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.updateTime(AchievePlayTimeRunnable.java:70) ~[?:?]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.lambda$run$0(AchievePlayTimeRunnable.java:59) ~[?:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_281]
	at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_281]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.run(AchievePlayTimeRunnable.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[17:15:32] [Server thread/INFO]: l_KyRiOs_l issued server command: /aach book
[17:15:32] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to AdvancedAchievements v6.7.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1689) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1540) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.hm.achievement.listener.statistics.PlayerCommandsListener.onPlayerCommand(PlayerCommandsListener.java:41) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	... 19 more
[17:16:24] [Server thread/WARN]: [AdvancedAchievements] Task #15 for AdvancedAchievements v6.7.2 generated an exception
java.lang.NullPointerException: null
	at com.hm.achievement.utils.StatisticIncreaseHandler.shouldIncreaseBeTakenIntoAccount(StatisticIncreaseHandler.java:121) ~[?:?]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.updateTime(AchievePlayTimeRunnable.java:70) ~[?:?]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.lambda$run$0(AchievePlayTimeRunnable.java:59) ~[?:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_281]
	at java.util.Collections$UnmodifiableCollection.forEach(Unknown Source) ~[?:1.8.0_281]
	at com.hm.achievement.runnable.AchievePlayTimeRunnable.run(AchievePlayTimeRunnable.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```

**Comment by PyvesB** [comment]
Probably safer to check out the previous release commit: https://github.com/PyvesB/advanced-achievements/commit/64e933794c1fb59fe465e50b823397726d2e5c9b

Intermediary commits aren't necessarily tested thoroughly on the `master` branch and may correspond to work in progress, as you'll have experienced here :)

**Comment by dmetzler1988** [comment]
Hi,
sorry for late response - it seems to be great and works very well - i am currently on extended testings with configurations. But it looks good. Thanks for your help!
