### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by GameCharmer** [PyvesB/advanced-achievements#951]
:information_source: **Basic information**

* Advanced Achievements version: 6.7.2
* Minecraft version: 1.16.5
* [Wiki](https://github.com/PyvesB/advanced-achievements/wiki) read: Yes
* [Existing issues](https://github.com/PyvesB/advanced-achievements/issues) searched: Yes

:beetle: **Description**

Enable MySQL, place some blocks.  It looks like the field name should be `places` not `achievements_places`.  This could be due to the TablePrefix being used as a prepend to field names?

```
 SELECT * FROM achievements_places LIMIT 1;
+--------------------------------------+--------------+---------------------+
| playername                           | blockid      | achievements_places |
+--------------------------------------+--------------+---------------------+
| REDACTED                             | stone_bricks |                   2 |
+--------------------------------------+--------------+---------------------+
```

:page_facing_up: **Server logs**

````
[02:51:39] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to AdvancedAchievements v6.7.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:370) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.ItemStack.placeItem(ItemStack.java:220) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1356) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: com.hm.achievement.exception.DatabaseReadError: Database read error while retrieving Places.stone_bricks statistics.
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:42) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.getMultipleAchievementAmount(AbstractDatabaseManager.java:395) ~[?:?]
        at com.hm.achievement.db.CacheManager.getAndIncrementStatisticAmount(CacheManager.java:188) ~[?:?]
        at com.hm.achievement.listener.statistics.AbstractListener.lambda$updateStatisticAndAwardAchievementsIfAvailable$0(AbstractListener.java:71) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.hm.achievement.listener.statistics.AbstractListener.updateStatisticAndAwardAchievementsIfAvailable(AbstractListener.java:70) ~[?:?]
        at com.hm.achievement.listener.statistics.PlacesListener.onBlockPlace(PlacesListener.java:62) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor387.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        ... 21 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'places' in 'field list'
        at jdk.internal.reflect.GeneratedConstructorAccessor154.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2023) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        at com.hm.achievement.db.AbstractDatabaseManager.lambda$getMultipleAchievementAmount$9(AbstractDatabaseManager.java:389) ~[?:?]
        at com.hm.achievement.db.SQLReadOperation.executeOperation(SQLReadOperation.java:37) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.getMultipleAchievementAmount(AbstractDatabaseManager.java:395) ~[?:?]
        at com.hm.achievement.db.CacheManager.getAndIncrementStatisticAmount(CacheManager.java:188) ~[?:?]
        at com.hm.achievement.listener.statistics.AbstractListener.lambda$updateStatisticAndAwardAchievementsIfAvailable$0(AbstractListener.java:71) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.hm.achievement.listener.statistics.AbstractListener.updateStatisticAndAwardAchievementsIfAvailable(AbstractListener.java:70) ~[?:?]
        at com.hm.achievement.listener.statistics.PlacesListener.onBlockPlace(PlacesListener.java:62) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor387.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.5.jar:git-Spigot-89d6047-058b4df]
        ... 21 more

````

:wrench: **Configuration**

````

# Database type, sqlite, h2, postgresql or mysql. Do a full server restart for this to take effect.
DatabaseType: mysql

# Prefix added to the tables in the database. If you switch from the default tables names (no prefix),
# the plugin will attempt an automatic renaming. Otherwise you have to rename your tables manually.
# Do a full server restart for this to take effect.
TablePrefix: "achievements_"

# Specify additional options when opening a connection to a MySQL/PostgreSQL database. Start each option with &,
# for instance "&useUnicode=yes&characterEncoding=UTF-8". Make sure the key-value pairs themselves are URL encoded.
AdditionalConnectionOptions: ""

# Settings to connect to your MySQL/PostgreSQL database (ignored if sqlite).
# A PostgreSQL database address will be similar to jdbc:postgresql://localhost:5432/minecraft
DatabaseAddress: "jdbc:mysql://localhost:3306/minecraft"
DatabaseUser: REDACTED
DatabasePassword: REDACTED

````

**Comment by PyvesB** [comment]
Hello @GameCharmer ! 👋🏻 

That's very odd, Advanced Achievement will never attempt to rename the columns when `TablePrefix` is used, it will just attempt to rename the table itself:
```
"ALTER TABLE " + category.toDBName() + " RENAME TO " + databaseManager.getPrefix() + category.toDBName()
```

The column should not be `achievements_places`, it should have remained `places`. To rename the column, one must specify `RENAME COLUMN` instead.

Could you manually try running a SQL query similar to the following on your database:
```
ALTER TABLE achievements_places RENAME TO achievements2_places
```

Does the column get renamed again?

**Comment by GameCharmer** [comment]
@PyvesB that does solve it, and after a few restarts, the column remains `places`.  I wonder if this occurred when we migrated from flat file to MySQL.

Either way, thanks!

**Comment by PyvesB** [comment]
If you migrated the database using an automated tool or a SQL dump, that may have gotten confused with the table having the same name as one of its columns. Anyway, glad to hear that it's solved. 😉

**Comment by GameCharmer** [comment]
@PyvesB no migration other than changing the config.yml to point to MySQL instead of the flat file.  I was hoping that it'd automatically move everything over but didn't, and that's fine as everyone gets a nice fresh start to earn rewards again.

The downside though is that I'm finding this with more and more tables.  I just checked achievements_breaks and it's broken as well.

I'm going to wipe it all again and put things in their own dedicated table to avoid any further problems with using a prefix.

**Comment by PyvesB** [comment]
When you switched the database type to MySQL, did you change the `TablePrefix` parameter at the same time, or did you change it later on?
