### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by mojiansheng** [PyvesB/advanced-achievements#997]
Version: paper1.16.5
error_info：
[16:31:22 INFO]: [AdvancedAchievements] Enabling AdvancedAchievements v7.0.3
[16:31:22 INFO]: [AdvancedAchievements] Backing up and loading configuration files...
[16:31:23 ERROR]: Error occurred while enabling AdvancedAchievements v7.0.3 (Is it up to date?)
java.lang.NullPointerException: null
        at net.tnemc.core.common.api.Economy_TheNewEconomy.currencyNameSingular(Economy_TheNewEconomy.java:65) ~[?:?]
        at com.hm.achievement.config.RewardParser.parseMoneyReward(RewardParser.java:109) ~[?:?]
        at com.hm.achievement.config.RewardParser.parseRewards(RewardParser.java:86) ~[?:?]
        at com.hm.achievement.config.ConfigurationParser.parseAchievement(ConfigurationParser.java:374) ~[?:?]
        at com.hm.achievement.config.ConfigurationParser.parseAchievements(ConfigurationParser.java:322) ~[?:?]
        at com.hm.achievement.config.ConfigurationParser.loadAndParseConfiguration(ConfigurationParser.java:91) ~[?:?]
        at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:142) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Paper.jar:git-Paper-550]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[Paper.jar:git-Paper-550]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[Paper.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[Paper.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[Paper.jar:git-Paper-550]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[Paper.jar:git-Paper-550]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:241) ~[Paper.jar:git-Paper-550]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[Paper.jar:git-Paper-550]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[Paper.jar:git-Paper-550]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[16:31:23 INFO]: [AdvancedAchievements] Disabling AdvancedAchievements v7.0.3

**Comment by PyvesB** [comment]
Hello @mojiansheng ! 👋🏻 

As you can see in the top element of the stacktrace, Advanced Achievements is simply trying to retrieve the currency name from an economy plugin (this is part of the Vault API contract, see [here](https://github.com/MilkBowl/VaultAPI/blob/af58e675c37ff9bd3a219e48571065845bcb8806/src/main/java/net/milkbowl/vault/economy/Economy.java#L79)). Unfortunately, The New Economy is blowing up, either it's misconfigured or there's a bug somewhere. If you don't manage to sort things on your own, I suggest opening up a bug report here: https://github.com/TheNewEconomy/TNE-Bukkit

In the meantime, as a workaround you can remove all `Money` rewards in the Advanced Achievements configuration. 😉

**Comment by mojiansheng** [comment]
Other plug-ins can call it normally.

**Comment by mojiansheng** [comment]
> 你好@mojiansh！👋🏻
> 
> 正如您在堆栈跟踪的顶部元素中所看到的，AdvancedGoals只是试图从一个经济插件中检索货币名称(这是Vault API契约的一部分，请参见[这里](https://github.com/MilkBowl/VaultAPI/blob/af58e675c37ff9bd3a219e48571065845bcb8806/src/main/java/net/milkbowl/vault/economy/Economy.java#L79))。不幸的是，新经济正在崩溃，要么是配置不当，要么是某个地方出了问题。如果你不能自己解决问题，我建议在这里提出一个问题：[Https://github.com/TheNewEconomy/TNE-Bukkit](https://github.com/TheNewEconomy/TNE-Bukkit)
> 
> 同时，作为解决办法，您可以删除所有`Money`高级成就配置的奖励。😉

Other plug-ins can call it normally.

**Comment by PyvesB** [comment]
> Other plug-ins can call it normally.

Apparently not, a very quick search on the NewEconomy issue tracker highlighted similar problems with other plugins, for example BiomeFinder (see https://github.com/TheNewEconomy/TNE-Bukkit/issues/108). As suggested in my previous message, it's probably worth opening a new issue there. 😉

**Comment by mojiansheng** [comment]
> > Other plug-ins can call it normally.
> 
> Apparently not, a very quick search on the NewEconomy issue tracker highlighted similar problems with other plugins, for example BiomeFinder (see [TheNewEconomy/TNE-Bukkit#108](https://github.com/TheNewEconomy/TNE-Bukkit/issues/108)). As suggested in my previous message, it's probably worth opening a new issue there. 😉

It's normal when I use quickshop or trade.

**Comment by PyvesB** [comment]
Do leave a link here once you've posted the issue on the New Economy repository, so that we can easily have a three-way conversation with the author and take things from there.

**Comment by mojiansheng** [comment]
> 一旦你在新经济资源库上发布了这个问题，请在这里留下一个链接，这样我们就可以很容易地与作者进行三方面的调查，并从中获取一些东西。

https://github.com/TheNewEconomy/TNE-Bukkit/issues/458

**Comment by PyvesB** [comment]
The author of The New Economy seems to agree and suspects a problem with your TNE configuration. Closing in consequence.
